//tex2jax configuration
{ 
inlineMath: [["$","$"],["\\\\(","\\\\)"]], 
displayMath: [["$$","$$"],["\\[","\\]"]], 
processEscapes: true,
}

//TeX configuration
{
equationNumbers: { autoNumber: "all" },
Macros: {
        pd:"{\\partial}",
        bi:"{\\mathbb i}",
        bC:"{\\mathbb C}",
        bE:"{\\mathbb E}",
        bF:"{\\mathbb F}",
        bN:"{\\mathbb N}",
        bP:"{\\mathbb P}",
        bQ:"{\\mathbb Q}",
        bR:"{\\mathbb R}",
        bZ:"{\\mathbb Z}",
        cA:"{\\mathcal A}",
        cB:"{\\mathcal B}",
        cC:"{\\mathcal C}",
        cD:"{\\mathcal D}",
        cE:"{\\mathcal E}",
        cF:"{\\mathcal F}",
        cM:"{\\mathcal M}",
        cO:"{\\mathcal O}",
        cP:"{\\mathcal P}",
        cT:"{\\mathcal T}",
        half:"{\\frac{1}{2}}",
        cV:"{\\mathcal V}",
        cW:"{\\mathcal W}",
        bx:"{\\boldsymbol}",
        ud:"{\\mathrm{d}}",
        uD:"{\\mathrm{D}}",
        fh:"{\\mathfrak{h}}",
        fg:"{\\mathfrak{g}}",
        ft:"{\\mathfrak{t}}",
        fU:"{\\mathfrak{U}}",
        sG:"{\\mathscr{G}}",
        sA:"{\\mathscr{A}}",
        sB:"{\\mathscr{B}}",
        sC:"{\\mathscr{C}}",
        sE:"{\\mathscr{E}}",
        sH:"{\\mathscr{H}}",
        sO:"{\\mathscr{O}}",
        sM:"{\\mathscr{M}}",
        sS:"{\\mathscr{S}}",
        sU:"{\\mathscr{U}}",
        rH:"{\\mathrm{H}}",
        sR:"{\\mathscr{R}}",
        sT:"{\\mathscr{T}}",
        sD:"{\\mathscr{D}}",
        loto:"{\\longrightarrow}",
        lmto:"{\\longmapsto}",
        gal:"{\\alpha}",
        gbe:"{\\beta}",
        gga:"{\\gamma}",
        gde:"{\\delta}",
        gep:"{\\epsilon}",
        vp:"{\\varphi}",
        pbs:"{\\bar\pd^*}",
        pb:"{\\bar\pd}",
        ad:"{\\mathop{\\rm ad}\\nolimits}",
        Ad:"{\\mathop{\\rm Ad}\\nolimits}",
        Aut:"{\\mathop{\\rm Aut}\\nolimits}",
        End:"{\\mathop{\\rm End}\\nolimits}",
        Ker:"{\\mathop{\\rm Ker}\\nolimits}",
        Rank:"{\\mathop{\\rm Rank}\\nolimits}",
        Coker:"{\\mathop{\\rm Coker}\\nolimits}",
        im:"{\\mathop{\\rm im}\\nolimits}",
        Tr:"{\\mathop{\\rm Tr}\\nolimits}",
        D:"{\\mathop{\\rm D}\\nolimits}",
        be:"{\\begin{equation}}",
        ee:"{\\end{equation}}",
        bes:"{\\begin{equation*}}",
        ees:"{\\end{equation*}}",
        bea:"{\\begin{eqnarray}}",
        eea:"{\\end{eqnarray}}",
        beas:"{\\begin{eqnarray*}}",
        eeas:"{\\end{eqnarray*}}",
        ben:"{\\begin{eqnarray*}}",
        een:"{\\end{eqnarray*}}",
        bst:"{\\begin{split}}",
        est:"{\\end{split}}",
        bp:"{\\begin{proof}}",
        ep:"{\\end{proof}}",
        bex:"{\\begin{exercise}}",
        eex:"{\\end{exercise}}",
        bz:"{\\bar z}"
    }
}
